### PR TITLE
Abstractions addition

### PR DESCRIPTION
**Pull request by ghost**
- adds an entry for the Abstractions conference (Code and Supply)

### CODE REVIEW

**Comment by ghost** [comment]
Might want to "squash" the commits when you merge to make my two commits one (less noise in history)

**Comment by krantzinator** [comment]
@cmlang42 i thought you had to squash them prior to committing. learned a new thing about github's magic today!

**Comment by ghost** [comment]
I just learned about that 2 days ago, really. I was elated that I didn't have to rebase to squash on my own.  The maintainer for the repo I was working on shared [this blog post](https://github.com/blog/2141-squash-your-commits) with me.

**Comment by krantzinator** [comment]
Yes the time I tried to squash commits it turned into the biggest mess.
This is much better!

**Pull request merged**
